name: SME Banking CI Pipeline

on:
  push:
    branches:
      - main
      - qa
      - staging

  pull_request:
    branches:
      - main
      - qa
      - staging

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: '17'
          cache: maven

      - name: Build
        run: mvn clean package
